routes/web.php
<?php
/**
 * Wizard
 *
 * @link      https://aicode.cc/
 * @copyright 管宜尧 <mylxsw@aicode.cc>
 */

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'locale'], function () {
    // 如果启用 LDAP ，则不允许用户注册和重置密码
    $ldapDisabled = !ldap_enabled();
    Auth::routes([
        'reset'    => $ldapDisabled,
        'verify'   => $ldapDisabled,
        'register' => $ldapDisabled,
    ]);

    // 公共首页
    Route::get('/{catalog?}', 'HomeController@home')->name('home');
    // 项目公共页面
    Route::get('/project/{id}', 'ProjectController@project')->name('project:home');
    // 设置语言
    Route::get('/locale', 'HomeController@lang')->name('locale');

    // 分享页面
    Route::get('/s/{hash}', 'ShareController@page')->name('share:show');
    // 用户账号激活
    Route::get('/user/activate', 'UserController@activate')->name('user:activate');

    // 空白页，用于前端兼容
    Route::get('/blank', 'HomeController@blank')->name('blank');

    // 小工具
    Route::group(['middleware' => 'auth', 'prefix' => 'tools', 'as' => 'tools:'], function () {
        Route::post('json-to-markdown', 'ToolController@convertJsonToTable')
            ->name('json-to-markdown');
    });


    Route::group(['prefix' => 'project', 'middleware' => 'share', 'as' => 'project:'], function () {
        // 项目分享
        Route::get('/{id}/doc/{page_id}.json', 'DocumentController@getPageJSON')->name('doc:json');
        Route::get('/{id}/doc/{page_id}/histories/{history_id}.json',
            'HistoryController@getPageJSON')->name('doc:history:json');

        // 导出
        Route::post('/{id}/doc/{page_id}.pdf', 'ExportController@pdf')->name('doc:pdf');
    });

    Route::group(['prefix' => 'swagger', 'as' => 'swagger:'], function () {
        // 获取swagger文档内容
        Route::get('/{id}/doc/{page_id}.yml', 'DocumentController@getSwagger')->name('doc:yml');
        Route::get('/{id}/doc/{page_id}.json', 'DocumentController@getJson')->name('doc:json');
    });

    // 系统管理
    Route::group(['middleware' => ['auth', 'auth.admin'], 'prefix' => 'admin', 'as' => 'admin:'],
        function () {
            // 仪表盘
            Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

            // 用户组管理
            Route::get('/groups', 'GroupController@groups')->name('groups');
            Route::post('/groups', 'GroupController@add')->name('groups:add');
            Route::delete('/groups/{id}', 'GroupController@delete')->name('groups:del');
            Route::get('/groups/{id}', 'GroupController@info')->name('groups:view');
            Route::post('/groups/{id}/user', 'GroupController@addUser')->name('groups:users:add');
            Route::post('/groups/{id}', 'GroupController@update')->name('groups:update');
            Route::delete('/groups/{id}/users/{user_id}', 'GroupController@removeUser')
                ->name('groups:users:del');
            Route::post('/groups/{id}/projects', 'GroupController@grantProjects')
                ->name('groups:projects:add');

            // 用户管理
            Route::get('/users', 'UserController@users')->name('users');
            Route::get('/users/{id}', 'UserController@user')->name('user');
            Route::post('/users/{id}', 'UserController@updateUser')->name('user:update');
            Route::post('/users/{id}/groups', 'UserController@joinGroup')->name('user:join-group');

            // 项目目录管理
            Route::get('/catalogs', 'CatalogController@catalogs')->name('catalogs');
            Route::post('/catalogs', 'CatalogController@add')->name('catalogs:add');
            Route::get('/catalogs/{id}', 'CatalogController@info')->name('catalogs:view');
            Route::post('/catalogs/{id}', 'CatalogController@edit')->name('catalogs:edit');
            Route::delete('/catalogs/{id}', 'CatalogController@delete')->name('catalogs:delete');
            Route::delete('/catalogs/{id}/project/{project_id}', 'CatalogController@removeProject')
                ->name('catalogs:project:del');
        });

    // 文档搜索
    Route::group(['prefix' => 'search', 'as' => 'search:'], function () {
        Route::get('/', 'SearchController@search')->name('search');
    });

    Route::group(['middleware' => 'auth'], function () {
        // 个人首页
        Route::get('/home', 'ProjectController@home')->name('user:home');
        // 文件上传
        Route::post('/upload', 'FileController@imageUpload')->name('upload');

        // 用户信息
        Route::group(['prefix' => 'user', 'as' => 'user:'], function () {
            // 重新发送账号激活邮件
            Route::post('/activate/email', 'UserController@sendActivateEmail')
                ->name('activate:send');
            // 基本信息
            Route::get('/', 'UserController@basic')->name('basic');
            Route::post('/', 'UserController@basicHandle')->name('basic:handle');

            // 修改密码
            Route::get('/password', 'UserController@password')->name('password');
            Route::post('/password', 'UserController@passwordHandle')->name('password:handle');

            // 通知消息
            Route::get('/notifications', 'NotificationController@lists')->name('notifications');
            Route::put('/notifications/all', 'NotificationController@readAll')
                ->name('notifications:read-all');
            Route::put('/notifications/{notification_id}', 'NotificationController@read')
                ->name('notifications:read');

            // 个人模板管理
            Route::get('/templates', 'TemplateController@all')->name('templates');
            Route::delete('/templates/{id}', 'TemplateController@deleteTemplate')
                ->name('templates:delete');
            Route::get('/templates/{id}', 'TemplateController@edit')->name('templates:edit');
            Route::put('/templates/{id}', 'TemplateController@editHandle')
                ->name('templates:edit:handle');
        });

        Route::group(['prefix' => 'project', 'as' => 'project:'], function () {
            // 创建新项目
            Route::post('/', 'ProjectController@newProjectHandle')->name('new:handle');
            Route::delete('/{id}', 'ProjectController@delete')->name('delete');

            // 项目配置
            Route::get('/{id}/setting', 'ProjectController@setting')->name('setting:show');
            Route::post('/{id}/setting', 'ProjectController@settingHandle')->name('setting:handle');
            // 回收项目权限
            Route::delete('/{id}/privilege/{group_id}', 'ProjectController@groupPrivilegeRevoke')
                ->name('privilege:revoke');

            // 创建新的文档
            Route::get('/{id}/doc', 'DocumentController@newPage')->name('doc:new:show');
            Route::post('/{id}/doc', 'DocumentController@newPageHandle')->name('doc:new:handle');

            // 编辑文档
            Route::get('/{id}/doc/{page_id}', 'DocumentController@editPage')->name('doc:edit:show');
            Route::post('/{id}/doc/{page_id}', 'DocumentController@editPageHandle')
                ->name('doc:edit:handle');
            Route::delete('/{id}/doc/{page_id}', 'DocumentController@deletePage')
                ->name('doc:delete');

            // 文档同步
            Route::post('/{id}/doc/{page_id}/sync-from', 'DocumentController@syncFromRemote')
                ->name('doc:sync-from');

            // 文档分享
            Route::post('/{id}/doc/{page_id}/share', 'ShareController@create')->name('doc:share');

            // 阅读模式
            Route::get('/{id}/doc/{page_id}/read', 'DocumentController@readMode')->name('doc:read');

            // 文档评论
            Route::post('/{id}/doc/{page_id}/comments', 'CommentController@publish')
                ->name('doc:comment');

            // 文档附件
            Route::get('/{id}/doc/{page_id}/attachments', 'AttachmentController@page')
                ->name('doc:attachment');
            Route::delete('/{id}/doc/{page_id}/attachments/{attachment_id}',
                'AttachmentController@delete')->name('doc:attachment:delete');
            Route::post('/{id}/doc/{page_id}/attachments', 'AttachmentController@upload')
                ->name('doc:attachment:upload');

            // ajax获取文档是否过期
            Route::get('/{id}/doc/{page_id}/expired', 'DocumentController@checkPageExpired')
                ->name('doc:expired');

            // 文档历史记录
            Route::get('/{id}/doc/{page_id}/histories', 'HistoryController@pages')
                ->name('doc:history');
            Route::get('/{id}/doc/{page_id}/histories/{history_id}', 'HistoryController@page')
                ->name('doc:history:show');
            Route::put('/{id}/doc/{page_id}/histories/{history_id}', 'HistoryController@recover')
                ->name('doc:history:recover');

            // 关注项目
            Route::post('/{id}/favorite', 'ProjectController@favorite')->name('favorite');
        });


        // 文档比较
        Route::post('/doc/compare', 'CompareController@compare')->name('doc:compare');

        // 创建模板
        Route::post('/template', 'TemplateController@create')->name('template:create');

        // ajax获取操作历史
        Route::get('/operations/recently', 'OperationLogController@recently')
            ->name('operation-log:recently');


        Route::group(['prefix' => 'tag', 'as' => 'tag:'], function () {
            // 创建标签
            Route::post('/', 'TagController@store')->name('tag:store');
        });
    });
});

app/Http/Controllers/GroupController.php
<?php
/**
 * Wizard
 *
 * @link      https://aicode.cc/
 * @copyright 管宜尧 <mylxsw@aicode.cc>
 */

namespace App\Http\Controllers;


use App\Repositories\Catalog;
use App\Repositories\Group;
use App\Repositories\Project;
use App\Repositories\User;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class GroupController extends Controller
{
    /**
     * 用户组管理
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function groups()
    {
        return view('group.groups', [
            'op'     => 'groups',
            'groups' => Group::withCount('users')->withCount('projects')->get(),
        ]);
    }

    /**
     * 分组信息
     *
     * @param Request $request
     * @param         $id
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function info(Request $request, $id)
    {
        $group    = Group::where('id', $id)->firstOrFail();
        $subQuery = function ($query) use ($id) {
            $query->where('group_id', $id);
        };

        $usersForSelect = User::whereDoesntHave('groups', $subQuery)
            ->where('status', User::STATUS_ACTIVATED)
            ->get();

        $users = User::whereHas('groups', $subQuery)->get();

        $projects          = $group->projects()->with('catalog')->get();
        $projectsForSelect = Project::whereDoesntHave('groups', $subQuery)->with('catalog')->get();

        // 目录列表，可以按照目录的维度批量选择目录下所有的项目批量为用户组授权
        $catalogs = Catalog::all();

        return view('group.info', [
            'op'                  => 'groups',
            'group'               => $group,
            'users_for_select'    => $usersForSelect,
            'users'               => $users,
            'projects'            => $projects,
            'projects_for_select' => $projectsForSelect,
            'tab'                 => $request->input('tab', 'member'),
            'catalogs'            => $catalogs,
        ]);
    }

    /**
     * 添加用户到分组
     *
     * @param Request $request
     * @param         $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function addUser(Request $request, $id)
    {
        $this->validate(
            $request,
            [
                'users' => 'required|array',
            ],
            [
                'users.required' => '您没有选择要添加的用户',
            ]
        );

        $user_ids = $request->input('users');

        $group = Group::where('id', $id)->firstOrFail();
        $group->users()->attach($user_ids);

        $this->alertSuccess(__('common.operation_success'));

        return redirect(wzRoute('admin:groups:view', ['id' => $id, 'tab' => 'member']));
    }

    /**
     * 从分组移除用户
     *
     * @param Request $request
     * @param         $id
     * @param         $user_id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function removeUser(Request $request, $id, $user_id)
    {
        $group = Group::where('id', $id)->firstOrFail();
        $group->users()->detach($user_id);

        $this->alertSuccess(__('common.operation_success'));

        $origin    = $request->input('origin', 'admin:groups:view');
        $originTab = $request->input('origin_tab', 'member');
        $originId  = $request->input('origin_id', null);

        return redirect(wzRoute($origin, ['id' => $originId ?? $id, 'tab' => $originTab]));
    }

    /**
     * 新增分组
     *
     * @param Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function add(Request $request)
    {
        $this->validate(
            $request,
            [
                'name' => 'required|unique:wz_groups,name',
            ],
            [
                'name.required' => '分组名称不能为空',
                'name.unique'   => '分组名称已经存在',
            ]
        );

        Group::create([
            'name'    => $request->input('name'),
            'user_id' => \Auth::user()->id,
        ]);

        $this->alertSuccess(__('common.operation_success'));

        return redirect(wzRoute('admin:groups'));
    }

    /**
     * 更新分组信息
     *
     * @param Request $request
     * @param         $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        $this->validate(
            $request,
            [
                'name' => [
                    'required',
                    Rule::unique('wz_groups', 'name')->ignore($id),
                ]
            ],
            [
                'name.required' => '分组名不能为空',
                'name.unique'   => '分组名已经存在',
            ]
        );

        $group       = Group::where('id', $id)->firstOrFail();
        $group->name = $request->input('name');

        $group->save();

        $this->alertSuccess(__('common.operation_success'));

        return redirect(wzRoute('admin:groups:view', ['id' => $id, 'tab' => 'setting']));
    }

    /**
     * 分组删除
     *
     * @param Request $request
     * @param         $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Exception
     * @throws \Throwable
     */
    public function delete(Request $request, $id)
    {
        /** @var Group $group */
        $group = Group::where('id', $id)->firstOrFail();

        \DB::transaction(function () use ($group) {
            $group->users()->detach();
            $group->projects()->detach();

            $group->delete();
        });

        $this->alertSuccess(__('common.delete_success'));

        return redirect(wzRoute('admin:groups'));
    }

    /**
     * 批量为用户组赋予项目权限
     *
     * @param Request $request
     * @param         $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function grantProjects(Request $request, $id)
    {
        $this->validate(
            $request,
            [
                'projects'  => 'required|array',
                'privilege' => 'in:wr,r'
            ],
            [
                'projects.required' => '您没有选择要添加的项目',
            ]
        );

        $projects  = $request->input('projects');
        $privilege = $request->input('privilege', 'r');

        $projectIds = [];
        foreach ($projects as $pro) {
            if (starts_with($pro, '#')) {
                /** @var Catalog $catalog */
                $catalog = Catalog::where('id', trim($pro, '#'))->firstOrFail();
                foreach ($catalog->projects()->pluck('id')->toArray() as $projectId) {
                    $projectIds[] = (int)$projectId;
                }
            } else {
                $projectIds[] = (int)$pro;
            }
        }

        $projectIds = array_unique($projectIds, SORT_NUMERIC);

        $group = Group::where('id', $id)->firstOrFail();
        $group->projects()->detach($projectIds);
        $group->projects()->attach($projectIds, ['privilege' => $privilege == 'r' ? 2 : 1]);

        $this->alertSuccess(__('common.operation_success'));

        return redirect(wzRoute('admin:groups:view', ['id' => $id, 'tab' => 'project']));
    }
}

resources/views/group/groups.blade.php
@extends('layouts.admin')

@section('title', '用户组')
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ wzRoute('user:home') }}">@lang('common.home')</a></li>
        <li class="breadcrumb-item">系统管理</li>
        <li class="breadcrumb-item active">用户组管理</li>
    </ol>
@endsection
@section('admin-content')
    <div class="card">
        <div class="card-header">创建用户组</div>
        <div class="card-body">
            <form method="post"
                  action="{!! wzRoute('admin:groups:add') !!}">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="form-name" class="bmd-label-floating">用户组名称</label>
                    <input id="form-name" type="text" name="name" class="form-control" value="{{ old('name') }}" />
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-raised btn-primary" >创建用户组</button>
                </div>
            </form>
        </div>
    </div>

    <div class="card mt-3">
        <div class="card-header">用户组</div>
        <table class="table">
            <thead>
            <tr>
                <th>#</th>
                <th>用户组名称</th>
                <th>用户数</th>
                <th>项目数</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            @forelse($groups as $group)
                <tr>
                    <th scope="row">{{ $group->id }}</th>
                    <td><a href="{!! wzRoute('admin:groups:view', ['id' => $group->id]) !!}">{{ $group->name }}</a></td>
                    <td>{{ $group->users_count }}</td>
                    <td>{{ $group->projects_count }}</td>
                    <td>
                        <a href="{!! wzRoute('admin:groups:view', ['id' => $group->id]) !!}">
                            <i class="material-icons" title="管理">create</i>
                        </a>
                        &nbsp;&nbsp;
                        <a href="#" wz-form-submit data-form="#form-group-{{ $group->id }}"
                           data-confirm="确定要删除该分组？将会同步删除该分组分配的项目权限和用户关系">
                            <i class="material-icons text-danger" title="@lang('common.btn_delete')">delete_sweep</i>
                            <form id="form-group-{{ $group->id }}" method="post"
                                  action="{{ wzRoute('admin:groups:del', ['id' => $group->id]) }}">
                                {{ method_field('DELETE') }}{{ csrf_field() }}
                            </form>
                        </a>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" class="text-center">没有符合条件的信息！</td>
                </tr>
            @endforelse
            </tbody>
        </table>
    </div>
@endsection

resources/views/group/info.blade.php
@extends('layouts.admin')

@section('title', '用户组')
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ wzRoute('user:home') }}">@lang('common.home')</a></li>
        <li class="breadcrumb-item">系统管理</li>
        <li class="breadcrumb-item"><a href="{{ wzRoute('admin:groups') }}">用户组管理</a></li>
        <li class="breadcrumb-item active">{{ $group->name }}</li>
    </ol>
@endsection
@section('admin-content')
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="member-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">成员</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="project-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">项目</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="setting-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">设置</a>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
            <div class="card">
                <div class="card-header">添加成员</div>
                <div class="card-body">
                    <form method="post"
                          action="{!! wzRoute('admin:groups:users:add', ['id' => $group->id]) !!}">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <select name="users[]" style="width: 440px;" class="form-control select2-multiple" id="wz-user-select" multiple>
                                @foreach($users_for_select as $user)
                                    <option value="{{ $user->id }}" data-name="{{ $user->name }}" data-email="{{ $user->email }}">
                                        {{ $user->name }}（{{ $user->email }}）
                                    </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-raised">添加</button>
                            <a href="{!! route('admin:groups') !!}" class="btn btn-default">@lang('common.btn_back')</a>
                        </div>
                    </form>
                </div>
            </div>

            <div class="card mt-3">
                <div class="card-header">成员</div>
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>真实姓名</th>
                        <th>账号</th>
                        <th>注册时间</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($users as $user)
                        <tr>
                            <th scope="row">{{ $user->id }}</th>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->created_at->format('Y-m-d H:i') }}</td>
                            <td>
                                <a href="#" wz-form-submit data-form="#form-user-{{ $user->id }}"
                                   data-confirm="确定要将用户从该用户组移除？">
                                    <i class="material-icons text-danger" title="@lang('common.btn_delete')">delete_sweep</i>
                                    <form id="form-user-{{ $user->id }}" method="post"
                                          action="{!! wzRoute('admin:groups:users:del', ['id' => $group->id, 'user_id' => $user->id]) !!}">
                                        {{ method_field('DELETE') }}{{ csrf_field() }}
                                    </form>
                                </a>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5" class="text-center">没有符合条件的信息！</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            <div class="card mt-3">
                <div class="card-header">添加项目</div>
                <div class="card-body">
                    <form method="post"
                          action="{!! wzRoute('admin:groups:projects:add', ['id' => $group->id]) !!}">
                        {{ csrf_field() }}

                        <div class="alert alert-info" role="alert">
                            以“<b>#</b>”开头的选项为项目目录，选择该项会将该目录下所有项目权限批量赋予用户组。
                        </div>
                        <div class="form-group">
                            <select name="projects[]" style="width: 440px;" class="form-control select2-multiple" id="wz-project-select" multiple>
                                @foreach($catalogs as $cat)
                                    <option value="#{{ $cat->id }}" data-name="#{{ $cat->name }}">#{{ $cat->name }}</option>
                                @endforeach
                                @foreach($projects_for_select as $proj)
                                    @php
                                        $projectName = $proj->name . (empty($proj->catalog_id) ? '' : "（#{$proj->catalog->name}）");
                                    @endphp
                                    <option value="{{ $proj->id }}" data-name="{{ $projectName }}">
                                        {{ $projectName }}
                                    </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="privilege" value="wr"> @lang('project.group_write_enabled')
                                </label>
                            </div>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-raised">添加</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="card mt-3">
                <div class="card-header">@lang('common.project')</div>
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>@lang('project.project_name')</th>
                        <th>@lang('project.group_write_enabled')</th>
                        <th>@lang('common.operation')</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($projects as $project)
                        <tr>
                            <th scope="row">{{ $project->id }}</th>
                            <td>
                                <a href="{!! route('project:home', ['id' => $project->id]) !!}">{{ $project->name }}</a>
                                @if(!empty($project->catalog_id))
                                    <a target="_blank" class="badge badge-pill badge-info" href="{{ route('home', ['catalog' => $project->catalog_id]) }}">#{{ $project->catalog->name ?? '' }}</a>
                                @endif
                            </td>
                            <td>{{ $project->pivot->privilege == 1 ? __('common.yes') : __('common.no') }}</td>
                            <td>
                                <a href="#" wz-form-submit data-form="#form-project-{{ $project->id }}"
                                   data-confirm="确定要移除对该用户组对项目的访问权限吗？">
                                    <i class="material-icons text-danger" title="@lang('common.btn_delete')">delete_sweep</i>
                                    <form id="form-project-{{ $project->id }}" method="post"
                                          action="{!! wzRoute('project:privilege:revoke', ['id' => $project->id, 'group_id' => $group->id, 'redirect' => wzRoute('admin:groups:view', ['id' => $group->id])]) !!}">
                                        {{ method_field('DELETE') }}{{ csrf_field() }}
                                    </form>
                                </a>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="4" class="text-center">没有符合条件的信息！</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
        <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
            <div class="card mt-3">
                <div class="card-header">修改组名</div>
                <div class="card-body">
                    <form method="post"
                          action="{!! wzRoute('admin:groups:update', ['id' => $group->id]) !!}">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="form-name" class="bmd-label-floating">用户组名称</label>
                            <input id="form-name" type="text" name="name" class="form-control" value="{{ old('name', $group->name) }}" />
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-raised btn-primary" >保存</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>







@endsection

@push('stylesheet')
    <link href="/assets/vendor/select2/css/select2.min.css" rel="stylesheet">
    <link href="/assets/vendor/select2-bootstrap-theme/select2-bootstrap.min.css" rel="stylesheet">
@endpush

@push('script')
<script src="/assets/vendor/select2/js/select2.full.min.js"></script>
<script>
    $(function () {
        $.fn.select2.defaults.set("theme", "bootstrap");

        $('#wz-user-select').select2({
            placeholder: '选择用户',
            templateSelection: function (data, container) {
                return $(data.element).data('name');
            }
        });

        $('#wz-project-select').select2({
            placeholder: '选择项目',
            templateSelection: function (data, container) {
                return $(data.element).data('name');
            }
        });

        $('#{{ $tab ?? 'member' }}-tab').trigger('click');
    });
</script>
@endpush