routes/web.php
<?php
/**
 * Wizard
 *
 * @link      https://aicode.cc/
 * @copyright 管宜尧 <mylxsw@aicode.cc>
 */

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'locale'], function () {
    // 如果启用 LDAP ，则不允许用户注册和重置密码
    $ldapDisabled = !ldap_enabled();
    Auth::routes([
        'reset'    => $ldapDisabled,
        'verify'   => $ldapDisabled,
        'register' => $ldapDisabled,
    ]);

    // 公共首页
    Route::get('/{catalog?}', 'HomeController@home')->name('home');
    // 项目公共页面
    Route::get('/project/{id}', 'ProjectController@project')->name('project:home');
    // 设置语言
    Route::get('/locale', 'HomeController@lang')->name('locale');

    // 分享页面
    Route::get('/s/{hash}', 'ShareController@page')->name('share:show');
    // 用户账号激活
    Route::get('/user/activate', 'UserController@activate')->name('user:activate');

    // 空白页，用于前端兼容
    Route::get('/blank', 'HomeController@blank')->name('blank');

    // 小工具
    Route::group(['middleware' => 'auth', 'prefix' => 'tools', 'as' => 'tools:'], function () {
        Route::post('json-to-markdown', 'ToolController@convertJsonToTable')
            ->name('json-to-markdown');
    });


    Route::group(['prefix' => 'project', 'middleware' => 'share', 'as' => 'project:'], function () {
        // 项目分享
        Route::get('/{id}/doc/{page_id}.json', 'DocumentController@getPageJSON')->name('doc:json');
        Route::get('/{id}/doc/{page_id}/histories/{history_id}.json',
            'HistoryController@getPageJSON')->name('doc:history:json');

        // 导出
        Route::post('/{id}/doc/{page_id}.pdf', 'ExportController@pdf')->name('doc:pdf');
    });

    Route::group(['prefix' => 'swagger', 'as' => 'swagger:'], function () {
        // 获取swagger文档内容
        Route::get('/{id}/doc/{page_id}.yml', 'DocumentController@getSwagger')->name('doc:yml');
        Route::get('/{id}/doc/{page_id}.json', 'DocumentController@getJson')->name('doc:json');
    });

    // 系统管理
    Route::group(['middleware' => ['auth', 'auth.admin'], 'prefix' => 'admin', 'as' => 'admin:'],
        function () {
            // 仪表盘
            Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

            // 用户组管理
            Route::get('/groups', 'GroupController@groups')->name('groups');
            Route::post('/groups', 'GroupController@add')->name('groups:add');
            Route::delete('/groups/{id}', 'GroupController@delete')->name('groups:del');
            Route::get('/groups/{id}', 'GroupController@info')->name('groups:view');
            Route::post('/groups/{id}/user', 'GroupController@addUser')->name('groups:users:add');
            Route::post('/groups/{id}', 'GroupController@update')->name('groups:update');
            Route::delete('/groups/{id}/users/{user_id}', 'GroupController@removeUser')
                ->name('groups:users:del');
            Route::post('/groups/{id}/projects', 'GroupController@grantProjects')
                ->name('groups:projects:add');

            // 用户管理
            Route::get('/users', 'UserController@users')->name('users');
            Route::get('/users/{id}', 'UserController@user')->name('user');
            Route::post('/users/{id}', 'UserController@updateUser')->name('user:update');
            Route::post('/users/{id}/groups', 'UserController@joinGroup')->name('user:join-group');

            // 项目目录管理
            Route::get('/catalogs', 'CatalogController@catalogs')->name('catalogs');
            Route::post('/catalogs', 'CatalogController@add')->name('catalogs:add');
            Route::get('/catalogs/{id}', 'CatalogController@info')->name('catalogs:view');
            Route::post('/catalogs/{id}', 'CatalogController@edit')->name('catalogs:edit');
            Route::delete('/catalogs/{id}', 'CatalogController@delete')->name('catalogs:delete');
            Route::delete('/catalogs/{id}/project/{project_id}', 'CatalogController@removeProject')
                ->name('catalogs:project:del');
        });

    // 文档搜索
    Route::group(['prefix' => 'search', 'as' => 'search:'], function () {
        Route::get('/', 'SearchController@search')->name('search');
    });

    Route::group(['middleware' => 'auth'], function () {
        // 个人首页
        Route::get('/home', 'ProjectController@home')->name('user:home');
        // 文件上传
        Route::post('/upload', 'FileController@imageUpload')->name('upload');

        // 用户信息
        Route::group(['prefix' => 'user', 'as' => 'user:'], function () {
            // 重新发送账号激活邮件
            Route::post('/activate/email', 'UserController@sendActivateEmail')
                ->name('activate:send');
            // 基本信息
            Route::get('/', 'UserController@basic')->name('basic');
            Route::post('/', 'UserController@basicHandle')->name('basic:handle');

            // 修改密码
            Route::get('/password', 'UserController@password')->name('password');
            Route::post('/password', 'UserController@passwordHandle')->name('password:handle');

            // 通知消息
            Route::get('/notifications', 'NotificationController@lists')->name('notifications');
            Route::put('/notifications/all', 'NotificationController@readAll')
                ->name('notifications:read-all');
            Route::put('/notifications/{notification_id}', 'NotificationController@read')
                ->name('notifications:read');

            // 个人模板管理
            Route::get('/templates', 'TemplateController@all')->name('templates');
            Route::delete('/templates/{id}', 'TemplateController@deleteTemplate')
                ->name('templates:delete');
            Route::get('/templates/{id}', 'TemplateController@edit')->name('templates:edit');
            Route::put('/templates/{id}', 'TemplateController@editHandle')
                ->name('templates:edit:handle');
        });

        Route::group(['prefix' => 'project', 'as' => 'project:'], function () {
            // 创建新项目
            Route::post('/', 'ProjectController@newProjectHandle')->name('new:handle');
            Route::delete('/{id}', 'ProjectController@delete')->name('delete');

            // 项目配置
            Route::get('/{id}/setting', 'ProjectController@setting')->name('setting:show');
            Route::post('/{id}/setting', 'ProjectController@settingHandle')->name('setting:handle');
            // 回收项目权限
            Route::delete('/{id}/privilege/{group_id}', 'ProjectController@groupPrivilegeRevoke')
                ->name('privilege:revoke');

            // 创建新的文档
            Route::get('/{id}/doc', 'DocumentController@newPage')->name('doc:new:show');
            Route::post('/{id}/doc', 'DocumentController@newPageHandle')->name('doc:new:handle');

            // 编辑文档
            Route::get('/{id}/doc/{page_id}', 'DocumentController@editPage')->name('doc:edit:show');
            Route::post('/{id}/doc/{page_id}', 'DocumentController@editPageHandle')
                ->name('doc:edit:handle');
            Route::delete('/{id}/doc/{page_id}', 'DocumentController@deletePage')
                ->name('doc:delete');

            // 文档同步
            Route::post('/{id}/doc/{page_id}/sync-from', 'DocumentController@syncFromRemote')
                ->name('doc:sync-from');

            // 文档分享
            Route::post('/{id}/doc/{page_id}/share', 'ShareController@create')->name('doc:share');

            // 阅读模式
            Route::get('/{id}/doc/{page_id}/read', 'DocumentController@readMode')->name('doc:read');

            // 文档评论
            Route::post('/{id}/doc/{page_id}/comments', 'CommentController@publish')
                ->name('doc:comment');

            // 文档附件
            Route::get('/{id}/doc/{page_id}/attachments', 'AttachmentController@page')
                ->name('doc:attachment');
            Route::delete('/{id}/doc/{page_id}/attachments/{attachment_id}',
                'AttachmentController@delete')->name('doc:attachment:delete');
            Route::post('/{id}/doc/{page_id}/attachments', 'AttachmentController@upload')
                ->name('doc:attachment:upload');

            // ajax获取文档是否过期
            Route::get('/{id}/doc/{page_id}/expired', 'DocumentController@checkPageExpired')
                ->name('doc:expired');

            // 文档历史记录
            Route::get('/{id}/doc/{page_id}/histories', 'HistoryController@pages')
                ->name('doc:history');
            Route::get('/{id}/doc/{page_id}/histories/{history_id}', 'HistoryController@page')
                ->name('doc:history:show');
            Route::put('/{id}/doc/{page_id}/histories/{history_id}', 'HistoryController@recover')
                ->name('doc:history:recover');

            // 关注项目
            Route::post('/{id}/favorite', 'ProjectController@favorite')->name('favorite');
        });


        // 文档比较
        Route::post('/doc/compare', 'CompareController@compare')->name('doc:compare');

        // 创建模板
        Route::post('/template', 'TemplateController@create')->name('template:create');

        // ajax获取操作历史
        Route::get('/operations/recently', 'OperationLogController@recently')
            ->name('operation-log:recently');


        Route::group(['prefix' => 'tag', 'as' => 'tag:'], function () {
            // 创建标签
            Route::post('/', 'TagController@store')->name('tag:store');
        });
    });
});

resources/views/user/basic.blade.php
@extends('layouts.user')

@section('title', __('common.user_info'))
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ wzRoute('user:home') }}">@lang('common.home')</a></li>
        <li class="breadcrumb-item">个人中心</li>
        <li class="breadcrumb-item active">@lang('common.user_info')</li>
    </ol>
@endsection
@section('user-content')
    <div class="card">
        <div class="card-body">
            <form class="form-horizontal" method="post" action="{{ wzRoute('user:basic:handle') }}">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="editor-email" class="bmd-label-floating">@lang('common.email')</label>
                    <input type="text" class="form-control" value="{{ $user->email }}" id="editor-email"
                           name="email" readonly>
                </div>
                <div class="form-group">
                    <label for="editor-username" class="bmd-label-floating">@lang('common.username')</label>
                    <input type="text" class="form-control" value="{{ $user->name }}" id="editor-username"
                           name="username" {{ ldap_enabled() ? 'readonly' : '' }}>
                </div>

                @if (ldap_enabled())
                    <div class="form-group">
                        <label for="editor-objectguid" class="bmd-label-floating">LDAP 对象ID</label>
                        <input type="text" class="form-control" value="{{ $user->objectguid }}" id="editor-objectguid"
                               name="objectguid" readonly>
                    </div>
                @endif

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit"
                                class="btn btn-success btn-raised" {{ ldap_enabled() ? 'disabled' : '' }}>@lang('common.btn_save')</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/user/notifications.blade.php
@extends('layouts.user')

@section('title', '通知')
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ wzRoute('user:home') }}">@lang('common.home')</a></li>
        <li class="breadcrumb-item">个人中心</li>
        <li class="breadcrumb-item active">通知</li>
    </ol>
@endsection
@section('user-content')

    <div class="card">
        <div class="card-body">
            <div class="btn-group wz-nav-control">
                <form action="{{ route('user:notifications:read-all') }}" method="post" id="form-notifications-readall">{{ method_field('PUT') }}{{ csrf_field() }}</form>
                <button class="btn btn-primary btn-raised" wz-form-submit data-form="#form-notifications-readall">全部标记为已读</button>
            </div>

            <table class="table table-hover wz-message-table">
                @forelse($notifications as $notification)
                    <tr class="{{ is_null($notification->read_at) ? 'warning' : '' }}">
                        <td style="width: 145px;">{{ $notification->created_at->format('Y-m-d H:i') }}</td>
                        <td>
                            {!! $notification->data['message'] !!}
                            @if(is_null($notification->read_at))
                            <span class="wz-message-read d-none">
                                <a href="#" class="fa fa-check wz-message-read-btn" title="设为已读"
                                   data-url="{{ wzRoute('user:notifications:read', ['notification_id' => $notification->id]) }}"></a>
                            </span>
                            @endif
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td class="text-center">没有符合条件的信息！</td>
                    </tr>
                @endforelse
            </table>

            <div class="wz-pagination">
                {{ $notifications->links() }}
            </div>
        </div>
    </div>

@endsection

@push('script')
<script>
    $(function () {
        $('.wz-message-read-btn').on('click', function(e) {
            e.preventDefault();
            var $this = $(this);
            var url = $(this).data('url');
            $.wz.request('put', url, {}, function(data) {
                $this.parents('tr').removeClass('warning');
                $this.parents('.wz-message-read').remove();
            });
        });
    });
</script>
@endpush

resources/views/user/password.blade.php
@extends('layouts.user')

@section('title', __('common.change_password'))
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ wzRoute('user:home') }}">@lang('common.home')</a></li>
        <li class="breadcrumb-item">个人中心</li>
        <li class="breadcrumb-item active">@lang('common.change_password')</li>
    </ol>
@endsection
@section('user-content')
    <div class="card">
        <div class="card-body">
            <form class="form-horizontal" method="post" action="{{ wzRoute('user:password:handle') }}">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="editor-original_password" class="bmd-label-floating">@lang('passwords.original_password')</label>
                    <input type="password" class="form-control" value="{{ old('original_password') }}"
                           id="editor-original_password"
                           name="original_password" >
                </div>
                <div class="form-group">
                    <label for="editor-new-password" class="bmd-label-floating">@lang('passwords.new_password')</label>
                    <input type="password" class="form-control" id="editor-new-password"
                           name="password" value="{{ old('password') }}">
                </div>
                <div class="form-group">
                    <label for="editor-new-password-confirm" class="bmd-label-floating">@lang('passwords.new_password_confirm')</label>
                    <input type="password" class="form-control" id="editor-new-password-confirm"
                           name="password_confirmation" value="{{ old('password_confirmation') }}">
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success btn-raised">@lang('common.btn_save')</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/user/templates.blade.php
@extends('layouts.user')

@section('title', '模板管理')
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ wzRoute('user:home') }}">@lang('common.home')</a></li>
        <li class="breadcrumb-item">个人中心</li>
        <li class="breadcrumb-item active">模板管理</li>
    </ol>
@endsection
@section('user-content')
    <div class="card">
        <div class="card-body">
            <table class="table table-hover wz-message-table">
                <thead>
                <tr>
                    <th style="width: 56px;">类型</th>
                    <th style="min-width: 200px;">名称</th>
                    <th>描述</th>
                    <th style="width: 85px;">操作</th>
                </tr>
                </thead>
                <tbody>
                @forelse($templates as $temp)
                    <tr>
                        <td>
                            <p><img src="/assets/{{ $temp->type == 1 ? 'swagger' : 'markdown' }}.png" style="width: 20px;" title="{{ $temp->type == 1 ? 'swagger' : 'markdown' }}"/></p>
                            @if($temp->scope == \App\Repositories\Template::SCOPE_GLOBAL)
                                <p><i class="material-icons" title="与他人共享的">people</i></p>
                            @endif
                        </td>
                        <td>
                            <p><a href="{{ wzRoute('user:templates:edit', ['id' => $temp->id]) }}">{{ $temp->name }}</a></p>
                            <p style="color: #808080;">{{ $temp->updated_at->format('Y-m-d H:i') }}</p>
                        </td>
                        <td>{{ $temp->description }}</td>
                        <td>
                            <a href="{{ wzRoute('user:templates:edit', ['id' => $temp->id]) }}"><i class="material-icons" title="编辑">create</i> </a>
                            &nbsp;
                            <a href="#" wz-form-submit data-form="#form-template-{{ $temp->id }}"
                               data-confirm="确定要删除该模板？">
                                <i class="material-icons text-danger" title="@lang('common.btn_delete')">delete_sweep</i>
                                <form id="form-template-{{ $temp->id }}" method="post"
                                      action="{{ wzRoute('user:templates:delete', ['id' => $temp->id]) }}">
                                    {{ method_field('DELETE') }}{{ csrf_field() }}
                                </form>
                            </a>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td class="text-center" colspan="4">没有符合条件的信息！</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
    </div>

@endsection

resources/views/user/user.blade.php
@extends('layouts.admin')

@section('title', '用户管理')
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ wzRoute('user:home') }}">@lang('common.home')</a></li>
        <li class="breadcrumb-item">系统管理</li>
        <li class="breadcrumb-item"><a href="{{ wzRoute('admin:users') }}">用户管理</a></li>
        <li class="breadcrumb-item active">{{ $user->name }}</li>
    </ol>
@endsection
@section('admin-content')

    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="basic-tab" data-toggle="tab" href="#basic" role="tab" aria-controls="basic" aria-selected="true">基本信息</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="user-group-tab" data-toggle="tab" href="#user-group" role="tab" aria-controls="user-group" aria-selected="false">用户组</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="project-tab" data-toggle="tab" href="#project" role="tab" aria-controls="project" aria-selected="false">项目</a>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="basic" role="tabpanel" aria-labelledby="basic-tab">
            <div class="card">
                <div class="card-body">
                    @if($user->id == Auth::user()->id)
                        <div class="alert alert-warning" role="alert">
                            目前系统不支持在 “用户管理” 功能下修改当前登录用户的信息。
                        </div>
                    @endif

                    <form class="form-horizontal" method="post" action="{{ wzRoute('admin:user:update', ['id' => $user->id])  }}" style="max-width: 300px;">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="editor-email" class="bmd-label-floating">@lang('common.email')</label>
                            <input type="text" class="form-control" value="{{ $user->email }}" id="editor-email"
                                   name="email" readonly>
                        </div>
                        <div class="form-group">
                            <label for="editor-username" class="bmd-label-floating">@lang('common.username')</label>
                            <input type="text" class="form-control" value="{{ $user->name }}" id="editor-username"
                                   name="username" {{ ($user->id == Auth::user()->id || ldap_enabled()) ? 'readonly':'' }}>
                        </div>

                        @if(ldap_enabled())
                            <div class="form-group">
                                <label for="editor-objectguid" class="bmd-label-floating">LDAP 对象ID</label>
                                <input type="text" class="form-control" value="{{ $user->objectguid }}" id="editor-objectguid"
                                       name="objectguid" readonly>
                            </div>
                        @endif

                        <div class="form-group">
                            <label class="bmd-label-floating">角色</label>
                            <div class="radio mt-2">
                                <label class="radio-inline">
                                    <input type="radio" name="role" value="1" {{ $user->role == 1 ? 'checked':'' }} {{ $user->id == 1 ? 'disabled': '' }}> 普通用户
                                </label>
                                <label class="radio-inline">
                                    <input type="radio" name="role" value="2" {{ $user->role == 2 ? 'checked':'' }} {{ $user->id == 1 ? 'disabled': '' }}> 管理员
                                </label>

                                @if($user->id == 1)
                                    <i class="fa fa-question-circle" data-toggle="tooltip" title="该用户为系统初始管理员，不允许修改其身份"></i>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="editor-status" class="bmd-label-floating">状态</label>
                            <select id="editor-status" name="status" class="form-control"  {{ $user->id == Auth::user()->id ? 'disabled':'' }}>
                                <option value="0" {{ $user->status == 0 ? 'selected':'' }}>未激活</option>
                                <option value="1" {{ $user->status == 1 ? 'selected':'' }}>已激活</option>
                                <option value="2" {{ $user->status == 2 ? 'selected':'' }}>已禁用</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-success btn-raised"  {{ $user->id == Auth::user()->id ? 'disabled':'' }}>保存</button>
                            <a class="btn btn-default" href="{{ wzRoute('admin:users') }}">返回</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="user-group" role="tabpanel" aria-labelledby="user-group-tab">

            <div class="card">
                <div class="card-header">加入用户组</div>
                <div class="card-body">
                    <form method="post"
                          action="{!! wzRoute('admin:user:join-group', ['id' => $user->id]) !!}">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <select name="groups[]" style="width: 440px;" class="form-control select2-multiple" id="wz-group-select" multiple>
                                @foreach($group_for_select as $group)
                                    <option value="{{ $group->id }}" data-name="{{ $group->name }}">
                                        {{ $group->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-raised">加入</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="card mt-3">
                <div class="card-header">已加入的用户组</div>
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>用户组名称</th>
                        <th>项目数</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($user->groups()->withCount('projects')->get() as $group)
                        <tr>
                            <td>{{ $group->id }}</td>
                            <td>{{ $group->name }}</td>
                            <td>{{ $group->projects_count }}</td>
                            <td>
                                <form id="form-user-{{ $user->id }}" method="post"
                                      action="{!! wzRoute('admin:groups:users:del', ['id' => $group->id, 'user_id' => $user->id, 'origin' => 'admin:user', 'origin_id' => $user->id,  'origin_tab' => 'user-group']) !!}">
                                    {{ method_field('DELETE') }}{{ csrf_field() }}
                                </form>
                                <a href="#" wz-form-submit data-form="#form-user-{{ $user->id }}"
                                   data-confirm="确定要将用户从该用户组移除？">
                                    <i class="material-icons text-danger" title="解除">remove_circle_outline</i>
                                </a>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="4" class="text-center">没有符合条件的信息！</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
        <div class="tab-pane fade" id="project" role="tabpanel" aria-labelledby="project-tab">
            <div class="card mt-3">
                <div class="card-header">创建的项目</div>
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>项目名称</th>
                        <th>文档数</th>
                        <th>创建时间</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($user->projects()->with('catalog')->withCount('pages')->get() as $proj)
                        <tr>
                            <td>{{ $proj->id }}</td>
                            <td>
                                <a href="{!! route('project:home', ['id' => $proj->id]) !!}">{{ $proj->name }}</a>
                                @if(!empty($proj->catalog_id))
                                    <a target="_blank" class="badge badge-pill badge-info" href="{{ route('home', ['catalog' => $proj->catalog_id]) }}">#{{ $proj->catalog->name ?? '' }}</a>
                                @endif
                            </td>
                            <td>{{ $proj->pages_count }}</td>
                            <td>{{ $proj->created_at }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="3" class="text-center">没有符合条件的信息！</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('stylesheet')
    <link href="/assets/vendor/select2/css/select2.min.css" rel="stylesheet">
    <link href="/assets/vendor/select2-bootstrap-theme/select2-bootstrap.min.css" rel="stylesheet">
@endpush

@push('script')
    <script src="/assets/vendor/select2/js/select2.full.min.js"></script>
    <script>
    $(function () {
        // 鼠标经过提示
        $('[data-toggle="tooltip"]').tooltip({
            delay: { "show": 500, "hide": 100 }
        });

        $.fn.select2.defaults.set("theme", "bootstrap");

        $('#wz-group-select').select2({
            placeholder: '选择组',
            templateSelection: function (data, container) {
                return $(data.element).data('name');
            }
        });

        $('#{{ $tab ?? 'basic' }}-tab').trigger('click');
    });
</script>
@endpush